config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#loading'
  get "graph", to: 'pages#graph'
  get "calender", to: 'pages#calender'
  # match "user_root" => 'superpowers#landing'

  resources :buddies, only: [:show]
  resources :users, only: [:update, :index]
  resources :tasks do
    resources :occurances
  end

  get :edit_profile, to: 'users#edit_profile'
  patch :update_profile, to: 'users#update_profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buddy.rb
class Buddy < ApplicationRecord
  belongs_to :user
end

app/models/occurance.rb
class Occurance < ApplicationRecord
  belongs_to :task

  def mark_as_done

  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :occurances, dependent: :destroy
  validates :name, presence: true
  validates :category, presence: true

  scope :done, -> { joins(:occurances).where(occurances: { done: true, date: Date.today }) }

  def done!
    occurances.find_by(date: Date.today).update!(done: true)
  end


  def color
    case category
    when 'sport' then '#F5C44D'
    when 'health' then '#A0E295'
    when 'hobby' then '#FF8954'
    when 'business' then '#2FC2FF'
    end
  end

  def logo
    case category
    when 'sport' then "sport.png"
    when 'health' then "health.png"
    when 'hobby' then "hobby.png"
    when 'business' then "business.png" 
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks, dependent: :destroy

  def current_tasks
    Task.joins(:occurances).where(occurances: {date: Date.today, done: false}, tasks: {user_id: id} )
  end

  def score
    {
      health: score_by_category(:health),
      sport: score_by_category(:sport),
      business: score_by_category(:business),
      hobby: score_by_category(:hobby)
    }
  end

  # private

  def score_by_category(category)
    (number_task_done(category) + base_score(category)) * 100 / number_task_total(category)
  end

  def number_task_done(category)
    tasks.where(category: category).done.count
  end

  def base_score(category)
    send("category_#{category}")
  end

  def number_task_total(category)
    tasks.where(category: category).count + base_score(category)
  end


  # graph test
  def tasks_by_category(category)
    Occurance.joins(:task).where(tasks: {user_id: id, category: category} ).where("occurances.date <= ?", Date.today).count
  end

  def tasks_done_by_category(category)
    Occurance.joins(:task).where(tasks: {user_id: id, category: category}, done: true ).where("occurances.date <= ?", Date.today).count
  end

  def tasks_done
    Occurance.joins(:task).where(tasks: {user_id: id}, done: true ).count
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :check_profile!, if: :current_user
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_general_score, if: :current_user

  def disable_nav
    @disable_nav = true
  end

  def set_general_score
     @general_score = current_user.tasks.done.count
  end





  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :category_health, :category_sport, :category_business, :category_hobby])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :category_health, :category_sport, :category_business, :category_hobby])
  end

  def check_profile!
    redirect_to edit_profile_path if current_user.tasks.none?
  end

  # app/controllers/application_controller.rb

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/buddies_controller.rb
class BuddiesController < ApplicationController
  # before_action :set_buddy, only: [:show ]

  def show
    @user = User.all
  end




end

app/controllers/occurances_controller.rb
class OccurancesController < ApplicationController

  def edit
  end

  def update!

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home, :loading]
  before_action :disable_nav, only: [:loading]
  before_action :set_general_score, if: :current_user

  def home
  end

  def loading
  end

  def graph

  end

  def set_general_score
    @general_score = current_user.tasks.done.count
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy];
  skip_before_action :verify_authenticity_token, only: [:update]

  def index
    @user = current_user
    @task = Task.new
    @tasks = @user.current_tasks
    @weather = MeteoApiService.new("Lyon").call
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def update
    @task.done!

    # redirect_to tasks_path
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    if @task.save
      generate_occurances(@task)
      # redirect_to tasks_path
    else
      render :new
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_url, notice: 'Task successfully removed'
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :category)
  end

  def generate_occurances(task)
    60.times do |i|
      data = i.days.from_now
      Occurance.create!(task: task, date: data, done: false)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :check_profile!

  def edit_profile
  end

  def update_profile
    current_user.update!(user_params)
    GenerateTasks.new.call(current_user)
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:category_sport, :category_business, :category_hobby, :category_health)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/buddies/show.html.erb
<%= render "shared/banner" %>
<div class="containergeneral">
  <div class="test">
    <span class="typed-js" data-controller="typed-js"></span>

    <div class="progressivebar">

      <% current_user.score.each do |category, value| %>
        <%= category %>:
        <progress class="progress-bar category-bar" value="<%= value %>" max="100"></progress>
      <% end %>
      <br>
    </div>
  </div>

<div>
  <% if @general_score < 5 %>
    <%= image_tag 'nakedloutrelandinggif.gif', size: "160", class: "nakedloutre" %>
  <% else %>
    <%= image_tag "SLkissgif.gif", size: "160", class: "belleloutre" %>
  <% end %>
</div>
<%= image_tag'blackhole.png',class: 'blackhole', size: "20" %>
<div class="progressive">
  <p class="xp">XP</p>
  <progress class="progress-bar xp-bar" value="<%= @general_score %>" max="18"></progress>

</div>

<%= render "tasks/navbar" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BUDDY</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= favicon_link_tag 'favicon.ico/favicon.ico' %>

    <title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">

  </head>

  <body>

    <%= yield %>
    <%# <%= current_user&.email %>
  </body>
</html>

app/views/pages/Loading.html.erb
  <title>BUDDY</title>
</head>
<body>

  <div class="container" style="justify-items:center;align-items:center">
      <%= image_tag("cloudbuddy.png", :class => "cloudbuddy", :style => "width: 377px, ;height: 800px; ")%>
      <div class="flex", style = "position: absolute;top: 285px;right: 19px; ;">
        <%= image_tag "superloutre.png", class: "superloutre"%>
      </div>
      <%= link_to "Meet your buddy", tasks_path, :style=>'color: red ;background-color: white ;width: 30px, ;height: 30px; font-size: 12px;border:none;'%>
  <div>
</body>

</html>

app/views/pages/calender.html.erb
<p>hi from calender</p>

app/views/pages/graph.html.erb
<%= render "shared/banner" %>
<div class="container-fluid">


    <h1 class="h1graph">Trophées</h1>

  <div class="loutregraph">
        <% if @general_score < 5 %>
          <%= image_tag 'Nakedottertopgif.gif', size: "120" %>
        <% else %>
          <%= image_tag "SLtopgif.gif", size: "120" %>
        <% end %>
  </div>

    <div class="colordiv">
      <div class="whitediv">
          <div class="lignesport">
                <div class="columncat">
                  <p id="categorytitles">Sport
                  <br>
                  <% current_user.tasks_done_by_category("sport")%>  <% current_user.tasks_by_category("sport")%></p>
                </div>
                <div class="columncat">
                  <% if current_user.tasks_done_by_category("sport")>= 3%>
                  <%= image_tag("bronze-medal.png") %>
                      <% else %>
                      <%= image_tag("bronze-medal.png", class:"grey") %>
                      <%end%>
                </div>
                <div class="columncat">
                  <% if current_user.tasks_done_by_category("sport")>= 4%>
                  <%= image_tag("silver-medal.png") %>
                      <% else %>
                      <%= image_tag("silver-medal.png", class:"grey") %>
                      <%end%>
                </div>
                <div class="columncat">
                  <% if current_user.tasks_done_by_category("sport")>= 5%>
                  <%= image_tag("gold-medal.png") %>
                      <% else %>
                      <%= image_tag("gold-medal.png", class:"grey") %>
                      <%end%>
                </div>
            </div>

          <div class="lignehealth">
              <div class="columncat">
                <p id="categorytitles">Health
                <br>
                <% current_user.tasks_done_by_category("health")%> <% current_user.tasks_by_category("health")%></p>
              </div>
              <div class="columncat">
                    <% if current_user.tasks_done_by_category("health")>= 3%>
                    <%= image_tag("bronze-medal.png") %>
                        <% else %>
                        <%= image_tag("bronze-medal.png", class:"grey") %>
                        <%end%>
                  </div>
                  <div class="columncat">
                    <% if current_user.tasks_done_by_category("health")>= 4%>
                    <%= image_tag("silver-medal.png") %>
                        <% else %>
                        <%= image_tag("silver-medal.png", class:"grey") %>
                        <%end%>
                  </div>
                  <div class="columncat">
                    <% if current_user.tasks_done_by_category("health")>= 5%>
                    <%= image_tag("gold-medal.png") %>
                        <% else %>
                        <%= image_tag("gold-medal.png", class:"grey") %>
                        <%end%>
                  </div>
            </div>

          <div class="lignehobby">
              <div class="columncat">
                <p id="categorytitles">Hobby
                <br>
                <% current_user.tasks_done_by_category("hobby")%>  <% current_user.tasks_by_category("hobby")%></p>
              </div>
              <div class="columncat">
                    <% if current_user.tasks_done_by_category("hobby")>= 3%>
                    <%= image_tag("bronze-medal.png") %>
                        <% else %>
                        <%= image_tag("bronze-medal.png", class:"grey") %>
                        <%end%>
                  </div>
                  <div class="columncat">
                    <% if current_user.tasks_done_by_category("hobby")>= 4%>
                    <%= image_tag("silver-medal.png") %>
                        <% else %>
                        <%= image_tag("silver-medal.png", class:"grey") %>
                        <%end%>
                  </div>
                  <div class="columncat">
                    <% if current_user.tasks_done_by_category("hobby")>= 5%>
                    <%= image_tag("gold-medal.png") %>
                        <% else %>
                        <%= image_tag("gold-medal.png", class:"grey") %>
                        <%end%>
                  </div>
          </div>

          <div class="lignebusiness">
                <div class="columncat">
                  <p id="categorytitle">Business
                  <br>
                  <% current_user.tasks_done_by_category("business")%> <% current_user.tasks_by_category("business")%></p>
                </div>
                  <div class="columncat">
                    <% if current_user.tasks_done_by_category("business")>= 3%>
                    <%= image_tag("bronze-medal.png") %>
                        <% else %>
                        <%= image_tag("bronze-medal.png", class:"grey") %>
                        <%end%>
                  </div>
                  <div class="columncat">
                    <% if current_user.tasks_done_by_category("business")>= 4%>
                    <%= image_tag("silver-medal.png") %>
                        <% else %>
                        <%= image_tag("silver-medal.png", class:"grey") %>
                        <%end%>
                  </div>
                  <div class="columncat">
                    <% if current_user.tasks_done_by_category("business")>= 5%>
                    <%= image_tag("gold-medal.png") %>
                        <% else %>
                        <%= image_tag("gold-medal.png", class:"grey") %>
                        <%end%>
                  </div>
              </div>
            </div>
    </div>
</div>
  <%= render "tasks/navbar" %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/loading.html.erb
<div class="land">

  <%= link_to tasks_path do %>
    <div class= "cloudbuddy">
      <% if @general_score < 5 %>
        <%= image_tag 'NakedLoutreHi.gif', class: "superloutre"  %>
      <% else %>
        <%= image_tag "SLflygif.gif", class: "superloutre2", size: "160"  %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_banner.html.erb
<div class="buddybanner">
  <span class="imgbanner"><%= image_tag ("BUDDYlogo.png") %></span>
</div>

app/views/tasks/_edit.html.erb
 <div class=" py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Edit your task</h3>
        <%= simple_form_for @task do |task| %>
          <%= task.input :name %>
          <%= task.collection_radio_buttons :category, [['sport', 'sport'] ,['health', 'health'], ['business', 'business'] ,['hobby', 'hobby']],:first, :last %>
          <%= task.submit class: 'btn btn-secondary' %>
          <%= link_to 'Back', tasks_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
 <div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Edit your task</h3>
        <%= simple_form_for @task do |task| %>
          <%= task.input :name %>
          <%= task.input :frequence, collection: ["Daily"," Weekly", "Monthly", "Yearly"] %>
          <%= task.input :category, collection: ["Sport", "Health", "Business", "Hobby"]%>
          <%= task.submit class: 'btn btn-warning' %>
          <%= link_to 'Back', tasks_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_navbar.html.erb
<div class="topnavbar">
  <div class="text">
    <div id=home class="icon">
      <%= link_to tasks_path do %>
        <%= image_tag("home.png") %>
      <% end %>
    </div>
    <div id=plus class="icon">
      <%= link_to new_task_path do %>
        <%= image_tag("plus.png") %>
      <% end %>
    </div>
    <div class="icon iconloutre">
      <%= link_to buddy_path(@current_user) do %>
        <%= image_tag("teteicone.png") %>
      <% end %>
    </div>
    <div id=graph class="icon">
      <%= link_to graph_path do %>
        <%= image_tag("graph.png") %>
      <% end %>
    </div>
    <div id=logout class="icon">
      <%= link_to destroy_user_session_path, method: :delete do %>
        <%= image_tag("logout.png") %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1> Edit your task ⚡️</h1>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<%= render "shared/banner" %>
<div class="container-task">
  <div class="weather">
    <%if @weather.downcase.include?("rain") %>
      <div class="rainy"></div>
    <% elsif%>
      <% @weather.downcase.include?("sun") %>
      <div class="sunny"></div>
    <% else %>
      <% @weather.downcase.include?("cloud") %>
      <div class="cloudy"></div>
    <% end %>
  </div>
  <div class="loutreindex">
        <% if @general_score < 5 %>
          <%= image_tag 'Nakedottertopgif.gif', size: "120" %>
        <% else %>
          <%= image_tag "SLtopgif.gif", size: "120" %>
        <% end %>
    </div>
      <div class= "row-">
        <div class="col-sm">
          <div data-controller="validate">
          <div class="popup" data-validate-target="validate">
            <h1>Bien joué ! Tu as validé cette tâche !</h1>
            <h2>C'est en avançant petit à petit qu'on fait de grandes choses, continues comme ça !</h2>
            <%= link_to tasks_path do %>
             <%=  image_tag("SLwdgif.gif", size: "200") %>
            <% end %>
          </div>
          <div class="bigbigcontainer" data-validate-target="container">
            <div class="col-sm">
              <% @tasks.each do |task| %>
                <div class="task", style="border-left: solid 10px <%= task.color %>">
                  <%= image_tag( task.logo ) %>
                  <p><%= task.name.capitalize %></p>
                  <div class="col-sm">
                    <%= simple_form_for task, remote: true, html: { 'data-action': "ajax:success->validate#displayPopup" } do |f| %>
                      <%= button_tag( :class => "btn") do %>
                      <%= image_tag "done.png" %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

    </div>
</div>
    <%= render "navbar" %>

app/views/tasks/new.html.erb
<%= render "shared/banner" %>
<div class="container" data-controller="validate">
  <div class="popup" data-validate-target="validate">
    <h1>Tâche ajoutée !</h1>
    <h2>Belle motivation ! une étape de passée, on continue comme ça ! </h2>
    <%= link_to tasks_path do %>
      <%=  image_tag("SLwdgif.gif", size: "200") %>
    <% end %>
  </div>
  <div class="bigbigcontainer" data-validate-target="container" >
    <div class="row">
      <div class="col-12 col-xs-6">
          <h1 id="addtasktitle">Ajoute une tâche</h1>
       <div class="pastequediv">
        <div class="bg-white rounded p-3 shadow">
          <%= simple_form_for @task, remote: true, html: { 'data-action': "ajax:success->validate#displayPopup" }  do |task| %>
          <div class="nameform">
            <%= task.input :name, :label => 'Nom',:required => false, placeholder: 'Ajoute ta tâche' %>
          </div>
          <p id="pcategory">Choisis une categorie</p>
          <div class="radiobtn">
            <%= task.collection_radio_buttons(:category, [['sport','sport'] ,['health', 'health'], ['business', 'business'] ,['hobby','hobby']], :first, :last) do |b| %>
            <%= b.label(:class => "#{b.text}_collection_radio_buttons") { b.radio_button + image_tag(b.text+'.png') } %>
            <% end %>
          </div>
          <div class="twobtn">
            <%= task.submit class: "creatbtn", :value => 'Créer', data: { disable_with: false }%>
            <% end %>
          </div>
        </div>
        <%= image_tag("SLflygif.gif", class: "SuperloutreFlying" )  %>
      </div>
    </div>
  </div>
</div>
<%= render "navbar" %>

app/views/users/edit_profile.html.erb
<%= render "shared/banner" %>
<div class="bannerquestions">
  <h1><strong>Qui es-tu ?</strong></h1>
  <p> Buddy a besoin de mieux te connaitre ! Suis ton instinct, es-tu plutôt : </p>
</div>
<div data-controller="parent">

  <%= simple_form_for(current_user, url: update_profile_path, html: {data: {'parent-target': 'form'}}) do |f| %>
    <%= f.error_notification %>

    <div class="d-none">
      <%= f.input :category_sport,
                  required: true,
                  input_html: { autocomplete: "category sport", min: '0', max: '2',  data: {'parent-target': "sportInput"} } %>

      <%= f.input :category_business,
                  required: true,
                  input_html: { autocomplete: "category business", min: '0', max: '2',  data: {'parent-target': "businessInput"} } %>

      <%= f.input :category_hobby,
                  required: true,
                input_html: { autocomplete: "category hobby", min: '0', max: '2', data: {'parent-target': "hobbyInput"} } %>

      <%= f.input :category_health,
                  required: true,
                  input_html: { autocomplete: "category health", min: '0', max: '2',  data: {'parent-target': "healthInput"} } %>
    </div>
  <% end %>
  <div class="container">
    <div class="questions">
      <% YAML.load_file('data/questions.yml').each do |question| %>
        <div class="d-none" data-parent-target="question" data-controller="enfant" data-enfant-category-value="<%= question["category"] %>" data-action="yes->parent#addCategory no->parent#next">
          <div class="options" data-enfant-target="option">
            <div class="questionss">
              <div class="photoyes" data-action="click->enfant#yes"><%= image_tag question["image-yes"]  %></div>
              <div class="photono" data-action="click->enfant#no"><%= image_tag question["image-no"]  %></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>